# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

dry:
  restore_package_cache: &restore_package_cache
    key: v1/node_modules/{{ checksum "package-lock.json" }}

  save_package_cache: &save_package_cache
    key: v1/node_modules/{{ checksum "package-lock.json" }}
    paths:
      - node_modules

jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: *restore_package_cache

      - run:
          name: Install prerequisites
          command: npm install

      - save_cache: *save_package_cache

      - run:
          name: Run tests
          command: yarn test
